fix module usage diamond dependency bug by adding cookies
i hit this bug:

$ fpm run -- samples/poople.syntran -- quiz
Error: function `len_dict_i64` parameter 0 `dict` requires type `dict_i64::dict_i64` but was given `poople::dict_i64`
   --> samples/poople.syntran:24:43
    |
 24 | println("Loaded ", dict_i64::len_dict_i64(&dict),
    |                                           ^^^^^ wrong argument type

dict really is the correct type, but line 24 imports it directly, while
dict's "let" declaration is imported indirectly via the poople lib

fixed by giving each type an id string "cookie" based on where it is
defined instead of how it is imported